# Local formula: `brew install --formula ./Formula/devbrain.rb` builds from
# the checkout (or a release tarball once tags exist). The published tap
# formula is generated by goreleaser; this one exists so clean-environment
# installs work before the tap does.
class Devbrain < Formula
  desc "Turn the prompts you write into a durable, queryable brain any agent can resume from"
  homepage "https://github.com/TheWeiHu/devbrain"
  url "https://github.com/TheWeiHu/devbrain/archive/refs/heads/go-rewrite.tar.gz"
  version "1.0.0"
  license "MIT"

  depends_on "go" => :build

  def install
    ldflags = "-s -w -X github.com/TheWeiHu/devbrain/internal/version.Version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/devbrain"
  end

  def caveats
    <<~EOS
      Wire this machine (hooks, skills, dashboard):
        devbrain install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devbrain version")
  end
end
