#!/usr/bin/env python3
"""devbrain — shared rules, defined ONCE instead of copied across capture.sh,
capture-response.sh, capture-memory.sh and import.py: redact() (secrets),
is_synthetic() (injected prompts), recap()/sample() (the one merged-#15 response
summarizer — closing sentence + head/middle body), remote_to_key() (routing).

Used directly by import.py and the capture-response heredoc, and as a CLI by the
bash hooks:
  printf %s "$text"   | devbrain_lib.py redact         -> redacted text
  printf %s "$prompt" | devbrain_lib.py prompt-filter  -> redacted prompt, or EMPTY if
                                                          synthetic (caller skips)
Pure stdlib, no import side effects, cheap to call per event.
"""
import re, sys

# High-confidence, prefix-anchored secret shapes. Equivalent to the sed program the
# bash hooks used to each carry — same patterns, one definition.
_REDACT = [
    (re.compile(r"sk-[A-Za-z0-9_-]{20,}"), "[REDACTED]"),
    (re.compile(r"(gh[pousr]_)[A-Za-z0-9]{20,}"), r"\1[REDACTED]"),
    (re.compile(r"github_pat_[A-Za-z0-9_]{20,}"), "[REDACTED]"),
    (re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}"), "[REDACTED]"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"), "[REDACTED]"),
    (re.compile(r"(Bearer )[A-Za-z0-9._-]{16,}"), r"\1[REDACTED]"),
]

def redact(text):
    if not text:
        return text
    for rx, repl in _REDACT:
        text = rx.sub(repl, text)
    return text

# Injected / synthetic "prompts" that aren't real user input — they only add noise.
SYNTHETIC_PREFIXES = (
    "<system_instruction>",
    "<system-reminder>",
    "<command-name>",
    "You are generating a short conversation title",
    "Caveat: The messages below were generated by the user",
    "Base directory for this skill:",
)

def is_synthetic(text):
    return bool(text) and text.lstrip().startswith(SYNTHETIC_PREFIXES)

# Conductor (and similar harnesses) prepend a <system_instruction>...</system_instruction>
# block to the user's FIRST real prompt of a workspace session. Without this strip the
# whole turn matches is_synthetic() and the real prompt is dropped — one lost prompt per
# Conductor session. Strip the leading block so the user's actual text is captured.
_SYS_INSTR = re.compile(r"^\s*<system_instruction>.*?</system_instruction>\s*", re.S)

def strip_wrappers(text):
    return _SYS_INSTR.sub("", text, count=1) if text else text

def recap(texts):
    """The turn's CLOSING sentence — the recap lives at the end of the final assistant
    message (per the CLAUDE.md convention). `texts` = the turn's assistant text blocks.
    This is the merged-#15 algorithm; the one recap definition for capture + import."""
    last_text = ""
    for t in texts:
        if t and t.strip():
            last_text = t
    chosen = ""
    for line in last_text.splitlines():
        s = re.sub(r"^[>\-\*\s]+", "", line.strip())
        if not s or s.startswith("#"):
            continue
        chosen = s   # keep going -> ends on the LAST substantive line
    if not chosen:
        chosen = re.sub(r"^[#>\-\*\s]+", "", last_text.strip())
    chosen = re.sub(r"\s+", " ", chosen).strip()
    parts = re.findall(r".+?[.!?](?:\s|$)", chosen)
    if parts:
        summary = parts[-1].strip()
        if len(summary) < 60 and len(parts) > 1:   # extend a too-short tail backwards
            summary = (parts[-2].strip() + " " + summary).strip()
    else:
        summary = chosen
    return summary[:500].strip()

def sample(texts):
    """A bounded head+middle SAMPLE of the whole turn's prose (the recap is the tail), so
    the log holds the reasoning, not just a headline. Short responses are kept whole; long
    ones are sampled to a fixed size with […] gap markers. Merged-#15 algorithm."""
    full = re.sub(r"\n{3,}", "\n\n", "\n\n".join(t.strip() for t in texts if t.strip()).strip())
    MAXCHARS, HEAD, MID = 4000, 2200, 1400   # MAXCHARS ~700 words; whole if under it
    if len(full) <= MAXCHARS:
        return full
    head = full[:HEAD].rsplit(" ", 1)[0].strip()            # snap off a partial word
    c = len(full) // 2
    mid = full[c - MID // 2 : c + MID // 2]
    mid = mid.split(" ", 1)[-1].rsplit(" ", 1)[0].strip()   # trim partial words both ends
    return head + "\n\n[…]\n\n" + mid + "\n\n[…]"

def remote_to_key(remote):
    """git remote URL -> <owner>__<repo> (lowercased, filesystem-safe), or None."""
    if not remote:
        return None
    url = remote[:-4] if remote.endswith(".git") else remote
    url = url.rstrip("/")
    repo = url.split("/")[-1]
    rest = url[: url.rfind("/")] if "/" in url else url
    owner = re.split(r"[:/]", rest)[-1] if rest != url else ""
    if not (owner and repo):
        return None
    return re.sub(r"[^a-z0-9._-]", "", f"{owner}__{repo}".lower().replace(" ", "-"))

# --- CLI for the bash hooks (stdin -> stdout, no trailing-newline surprises) ----------
def _main(argv):
    mode = argv[1] if len(argv) > 1 else ""
    data = sys.stdin.read()
    if mode == "redact":
        sys.stdout.write(redact(data))
    elif mode == "prompt-filter":
        # empty output signals "skip" (synthetic); otherwise the redacted prompt.
        # Strip the Conductor first-turn wrapper first so the real prompt survives.
        data = strip_wrappers(data)
        if data.strip() and not is_synthetic(data):
            sys.stdout.write(redact(data))
    else:
        sys.stderr.write(f"usage: devbrain_lib.py {{redact|prompt-filter}}\n")
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(_main(sys.argv))
