#!/usr/bin/env python3
"""devbrain — shared rules, defined ONCE instead of copied across capture.sh,
capture-response.sh, capture-memory.sh and import.py: redact() (secrets),
is_synthetic() (injected prompts), summarize() (recap), remote_to_key() (routing).

Used directly by import.py, and as a CLI by the bash hooks:
  printf %s "$text"   | devbrain_lib.py redact         -> redacted text
  printf %s "$prompt" | devbrain_lib.py prompt-filter  -> redacted prompt, or EMPTY if
                                                          synthetic (caller skips)
Pure stdlib, no import side effects, cheap to call per event.
"""
import re, sys

# High-confidence, prefix-anchored secret shapes. Equivalent to the sed program the
# bash hooks used to each carry — same patterns, one definition.
_REDACT = [
    (re.compile(r"sk-[A-Za-z0-9_-]{20,}"), "[REDACTED]"),
    (re.compile(r"(gh[pousr]_)[A-Za-z0-9]{20,}"), r"\1[REDACTED]"),
    (re.compile(r"github_pat_[A-Za-z0-9_]{20,}"), "[REDACTED]"),
    (re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}"), "[REDACTED]"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"), "[REDACTED]"),
    (re.compile(r"(Bearer )[A-Za-z0-9._-]{16,}"), r"\1[REDACTED]"),
]

def redact(text):
    if not text:
        return text
    for rx, repl in _REDACT:
        text = rx.sub(repl, text)
    return text

# Injected / synthetic "prompts" that aren't real user input — they only add noise.
SYNTHETIC_PREFIXES = (
    "<system_instruction>",
    "<system-reminder>",
    "<command-name>",
    "You are generating a short conversation title",
    "Caveat: The messages below were generated by the user",
    "Base directory for this skill:",
)

def is_synthetic(text):
    return bool(text) and text.lstrip().startswith(SYNTHETIC_PREFIXES)

MAX_SUMMARY_CHARS = 1000

def summarize(texts):
    """First 3 + last 3 sentences of the turn's FINAL assistant message, capped. `texts`
    is the list of assistant text blocks in the turn (in order)."""
    last_text = ""
    for t in texts:
        if t and t.strip():
            last_text = t
    lines = []
    for line in last_text.splitlines():
        s = re.sub(r"^[>\-\*\s]+", "", line.strip())
        if s and not s.startswith("#"):
            lines.append(s)
    body = re.sub(r"\s+", " ", " ".join(lines)).strip()
    if not body:
        return ""
    sents = [s for s in (x.strip() for x in re.split(r"(?<=[.!?])\s+", body)) if s]
    keep = sents if len(sents) <= 6 else sents[:3] + sents[-3:]
    out = " ".join(keep)
    return (out[:MAX_SUMMARY_CHARS].rstrip() + "…") if len(out) > MAX_SUMMARY_CHARS else out

def remote_to_key(remote):
    """git remote URL -> <owner>__<repo> (lowercased, filesystem-safe), or None."""
    if not remote:
        return None
    url = remote[:-4] if remote.endswith(".git") else remote
    url = url.rstrip("/")
    repo = url.split("/")[-1]
    rest = url[: url.rfind("/")] if "/" in url else url
    owner = re.split(r"[:/]", rest)[-1] if rest != url else ""
    if not (owner and repo):
        return None
    return re.sub(r"[^a-z0-9._-]", "", f"{owner}__{repo}".lower().replace(" ", "-"))

# --- CLI for the bash hooks (stdin -> stdout, no trailing-newline surprises) ----------
def _main(argv):
    mode = argv[1] if len(argv) > 1 else ""
    data = sys.stdin.read()
    if mode == "redact":
        sys.stdout.write(redact(data))
    elif mode == "prompt-filter":
        # empty output signals "skip" (synthetic); otherwise the redacted prompt
        if not is_synthetic(data):
            sys.stdout.write(redact(data))
    else:
        sys.stderr.write(f"usage: devbrain_lib.py {{redact|prompt-filter}}\n")
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(_main(sys.argv))
