#!/usr/bin/env python3
"""devbrain — shared rules, defined ONCE instead of copied across capture.sh,
capture-response.sh, capture-memory.sh and import.py: redact() (secrets),
is_synthetic() (injected prompts), recap()/sample() (the one merged-#15 response
summarizer — closing sentence + head/middle body), remote_to_key() (routing).

Used directly by import.py and the capture-response heredoc, and as a CLI by the
bash hooks:
  printf %s "$text"    | devbrain_lib.py redact            -> redacted text
  printf %s "$prompt"  | devbrain_lib.py prompt-filter     -> redacted prompt, or EMPTY if
                                                             synthetic (caller skips)
  printf %s "$payload" | devbrain_lib.py read-event FIELD  -> one normalized field from a
                                                             host-harness hook payload (JSON)
Pure stdlib, no import side effects, cheap to call per event.
"""
import json, os, re, sys

# High-confidence, prefix-anchored secret shapes. Equivalent to the sed program the
# bash hooks used to each carry — same patterns, one definition.
_REDACT = [
    (re.compile(r"sk-[A-Za-z0-9_-]{20,}"), "[REDACTED]"),
    (re.compile(r"(gh[pousr]_)[A-Za-z0-9]{20,}"), r"\1[REDACTED]"),
    (re.compile(r"github_pat_[A-Za-z0-9_]{20,}"), "[REDACTED]"),
    (re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}"), "[REDACTED]"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"), "[REDACTED]"),
    (re.compile(r"(Bearer )[A-Za-z0-9._-]{16,}"), r"\1[REDACTED]"),
]

def redact(text):
    if not text:
        return text
    for rx, repl in _REDACT:
        text = rx.sub(repl, text)
    return text

# Injected "prompts" that carry no user authorship at all — pure host-harness noise.
# Keep this list MINIMAL and bias toward keeping: a turn that merely embeds the user's
# text inside a harness wrapper (e.g. a <system_instruction> preamble) is still a real
# prompt and must be captured whole, wrapper and all. Only list markers whose entire
# body is machine-generated with zero user content.
SYNTHETIC_PREFIXES = (
    "<system-reminder>",
    "<command-name>",
    "You are generating a short conversation title",
    "Caveat: The messages below were generated by the user",
    "Base directory for this skill:",
)

def is_synthetic(text):
    return bool(text) and text.lstrip().startswith(SYNTHETIC_PREFIXES)

def recap(texts):
    """The turn's CLOSING sentence — the recap lives at the end of the final assistant
    message (per the CLAUDE.md convention). `texts` = the turn's assistant text blocks.
    This is the merged-#15 algorithm; the one recap definition for capture + import."""
    last_text = ""
    for t in texts:
        if t and t.strip():
            last_text = t
    chosen = ""
    for line in last_text.splitlines():
        s = re.sub(r"^[>\-\*\s]+", "", line.strip())
        if not s or s.startswith("#"):
            continue
        chosen = s   # keep going -> ends on the LAST substantive line
    if not chosen:
        chosen = re.sub(r"^[#>\-\*\s]+", "", last_text.strip())
    chosen = re.sub(r"\s+", " ", chosen).strip()
    parts = re.findall(r".+?[.!?](?:\s|$)", chosen)
    if parts:
        summary = parts[-1].strip()
        if len(summary) < 60 and len(parts) > 1:   # extend a too-short tail backwards
            summary = (parts[-2].strip() + " " + summary).strip()
    else:
        summary = chosen
    return summary[:500].strip()

def sample(texts):
    """A bounded head+middle SAMPLE of the whole turn's prose (the recap is the tail), so
    the log holds the reasoning, not just a headline. Short responses are kept whole; long
    ones are sampled to a fixed size with […] gap markers. Merged-#15 algorithm."""
    full = re.sub(r"\n{3,}", "\n\n", "\n\n".join(t.strip() for t in texts if t.strip()).strip())
    MAXCHARS, HEAD, MID = 4000, 2200, 1400   # MAXCHARS ~700 words; whole if under it
    if len(full) <= MAXCHARS:
        return full
    head = full[:HEAD].rsplit(" ", 1)[0].strip()            # snap off a partial word
    c = len(full) // 2
    mid = full[c - MID // 2 : c + MID // 2]
    mid = mid.split(" ", 1)[-1].rsplit(" ", 1)[0].strip()   # trim partial words both ends
    return head + "\n\n[…]\n\n" + mid + "\n\n[…]"

def remote_to_key(remote):
    """git remote URL -> <owner>__<repo> (lowercased, filesystem-safe), or None."""
    if not remote:
        return None
    url = remote[:-4] if remote.endswith(".git") else remote
    url = url.rstrip("/")
    repo = url.split("/")[-1]
    rest = url[: url.rfind("/")] if "/" in url else url
    owner = re.split(r"[:/]", rest)[-1] if rest != url else ""
    if not (owner and repo):
        return None
    return re.sub(r"[^a-z0-9._-]", "", f"{owner}__{repo}".lower().replace(" ", "-"))

# --- Event-field map: where each value lives in the harness's hook-event JSON ----------
# Background: the capture hooks are shell scripts, and the agent harness (Claude Code)
# feeds each one a JSON event on stdin — the user's prompt, the cwd, a tool call, etc.
# The hooks used to each pull fields out of that JSON inline with `jq` (a command-line
# JSON tool), so the SAME field paths were duplicated across four scripts. This dict is
# the single definition of those paths; a hook reads a field via `read-event` (below)
# instead of its own jq, so a path only ever changes in one place.
# $DEVBRAIN_HARNESS selects the map (default 'claude'); an unknown value falls back to
# 'claude' so a hook never breaks a turn.
_EVENT_FIELDS = {
    "claude": {
        "prompt":        ("prompt",),
        "cwd":           ("cwd",),
        "session":       ("session_id",),
        "transcript":    ("transcript_path",),
        "tool":          ("tool_name",),
        "command":       ("tool_input", "command"),
        "tool-response": ("tool_response",),   # value coerced to text (see _coerce_response)
    },
}

def _coerce_response(value):
    """tool_response shape varies by harness/version — an object with .stdout/.output, or
    a bare string. Coerce to printable text, matching the old jq coercion in capture-gbrain."""
    if isinstance(value, dict):
        for k in ("stdout", "output"):
            if isinstance(value.get(k), str):
                return value[k]
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return ""
    return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)

def read_event(payload, field, harness=None):
    """Return one NORMALIZED field from a host-harness hook payload (JSON text), or ''
    when the field is absent (matching jq's `// empty`). `harness` defaults to
    $DEVBRAIN_HARNESS or 'claude'; an unknown harness falls back to the claude mapping."""
    harness = harness or os.environ.get("DEVBRAIN_HARNESS") or "claude"
    mapping = _EVENT_FIELDS.get(harness) or _EVENT_FIELDS["claude"]
    path = mapping.get(field)
    if not path:
        return ""
    try:
        cur = json.loads(payload)
    except Exception:
        return ""
    for key in path:
        if not isinstance(cur, dict):
            return ""
        cur = cur.get(key)
        if cur is None:
            return ""
    if field == "tool-response":
        return _coerce_response(cur)
    if isinstance(cur, bool):
        return "true" if cur else "false"
    return cur if isinstance(cur, str) else str(cur)

# --- CLI for the bash hooks (stdin -> stdout, no trailing-newline surprises) ----------
def _main(argv):
    mode = argv[1] if len(argv) > 1 else ""
    data = sys.stdin.read()
    if mode == "redact":
        sys.stdout.write(redact(data))
    elif mode == "prompt-filter":
        # empty output signals "skip" (synthetic); otherwise the redacted prompt
        if not is_synthetic(data):
            sys.stdout.write(redact(data))
    elif mode == "read-event":
        # one normalized field per call (multiline-safe, like a single jq pull)
        sys.stdout.write(read_event(data, argv[2] if len(argv) > 2 else ""))
    else:
        sys.stderr.write("usage: devbrain_lib.py {redact|prompt-filter|read-event FIELD}\n")
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(_main(sys.argv))
