#!/usr/bin/env python3
"""devbrain import — one-time backfill so a fresh install has VALUE on day one.

Claude Code already holds months of history on the machine. This seeds the devbrain
data repo from it, so `gbrain search` returns hits immediately instead of after weeks
of forward capture. It is the batch counterpart to the live capture hooks:

  live  : capture.sh + capture-response.sh + capture-memory.sh  (one turn / session)
  batch : THIS                                                   (everything so far)

Three sources, harvested into the same layout the hooks write:
  1. ~/.claude/projects/<slug>/<session>.jsonl  — transcripts (prompts AND responses)
       -> projects/<key>/log/<day>/<worktree>.<session>.md   (PRIMARY; has ↳ recaps)
  2. ~/.claude/history.jsonl                     — typed prompts (fallback for sessions
       whose transcript was pruned)              -> same log layout, prompt-only
  3. ~/.claude/projects/<slug>/memory/*.md       — Claude's curated memory store, the
       longest-lived/highest-fidelity source     -> projects/<key>/memory/*.md

Safe by construction: redacts secrets, skips sessions already captured live, is
idempotent, and DRY-RUNS by default (prints a manifest; --apply to write).

Routing: a cache only records the cwd, and most of those dirs are gone. We recover the
<owner>__<repo> identity with a cascade (live git remote -> Conductor <project>
segment -> basename matched against live clones on disk -> alias -> miscellaneous), so
deleted worktrees still land in the right project instead of a junk bucket.
"""
import argparse, json, os, re, glob, subprocess, datetime, collections

# ---------------------------------------------------------------- redaction ----
REDACT = [
    (re.compile(r"sk-[A-Za-z0-9_-]{20,}"), "[REDACTED]"),
    (re.compile(r"(gh[pousr]_)[A-Za-z0-9]{20,}"), "[REDACTED]"),
    (re.compile(r"github_pat_[A-Za-z0-9_]{20,}"), "[REDACTED]"),
    (re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}"), "[REDACTED]"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"), "[REDACTED]"),
    (re.compile(r"(Bearer )[A-Za-z0-9._-]{16,}"), r"\1[REDACTED]"),
]
def redact(t):
    if not t:
        return t
    for rx, repl in REDACT:
        t = rx.sub(repl, t)
    return t

def sanitize(s):
    return re.sub(r"[^a-z0-9._-]", "", s.lower().replace(" ", "-"))

# ---------------------------------------------------------------- routing ------
def remote_to_key(remote):
    """git remote URL -> <owner>__<repo>, or None."""
    if not remote:
        return None
    url = remote[:-4] if remote.endswith(".git") else remote
    url = url.rstrip("/")
    repo = url.split("/")[-1]
    rest = url[: url.rfind("/")] if "/" in url else url
    owner = re.split(r"[:/]", rest)[-1] if rest != url else ""
    return sanitize(f"{owner}__{repo}") if owner and repo else None

def git_remote(path):
    try:
        return subprocess.run(["git", "-C", path, "remote", "get-url", "origin"],
                              capture_output=True, text=True, timeout=5).stdout.strip()
    except Exception:
        return ""

def build_remote_index(roots, depth=4):
    """basename -> <owner>__<repo>, from a scan of live clones on disk. This is how a
    DELETED worktree's <project> segment / basename is recovered to a real identity."""
    index = {}
    for root in roots:
        root = os.path.expanduser(root)
        if not os.path.isdir(root):
            continue
        for dirpath, dirs, _ in os.walk(root):
            d = dirpath[len(root):].count(os.sep)
            if d >= depth:
                dirs[:] = []
                continue
            if ".git" in dirs:
                key = remote_to_key(git_remote(dirpath))
                if key:
                    index.setdefault(os.path.basename(dirpath), key)
                dirs[:] = [x for x in dirs if x != ".git"]
    return index

def route(cwd, remote_index, aliases):
    """Resolution cascade -> (key, confidence)."""
    # 1. live path with a remote (still-present repo / worktree) — exact.
    if os.path.isdir(cwd):
        k = remote_to_key(git_remote(cwd))
        if k:
            return (k, "high")
    # 2. Conductor worktree: /conductor/workspaces/<proj>/<ws> or /conductor/repos/<proj>.
    m = re.search(r"/conductor/(?:workspaces|repos)/([^/]+)", cwd)
    seg = m.group(1) if m else os.path.basename(cwd.rstrip("/"))
    # 3. alias (renames a scan can't infer, e.g. RedditPages -> redlens).
    if seg in aliases:
        return (aliases[seg], "high")
    # 4. basename matched against live clones on disk.
    if seg in remote_index:
        return (remote_index[seg], "medium")
    # 5. unresolved -> shared bucket.
    return ("miscellaneous", "low")

# ------------------------------------------------------- prompt / response -----
SYNTHETIC_PREFIXES = (
    "<system_instruction>", "You are generating a short conversation title",
    "Caveat: The messages below were generated by the user", "<system-reminder>",
    "<command-name>", "Base directory for this skill:",
)
def text_of(content):
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        text = "".join(b.get("text", "") for b in content
                       if isinstance(b, dict) and b.get("type") == "text")
    else:
        return None
    text = text.strip()
    if not text or text.lstrip().startswith(SYNTHETIC_PREFIXES):
        return None
    return text

MAX_SUMMARY_CHARS = 1000
def summarize(texts):
    """First 3 + last 3 sentences of the turn's final assistant message (matches
    capture-response.sh)."""
    last_text = ""
    for t in texts:
        if t.strip():
            last_text = t
    lines = []
    for line in last_text.splitlines():
        s = re.sub(r"^[>\-\*\s]+", "", line.strip())
        if s and not s.startswith("#"):
            lines.append(s)
    body = re.sub(r"\s+", " ", " ".join(lines)).strip()
    if not body:
        return ""
    sents = [s for s in (x.strip() for x in re.split(r"(?<=[.!?])\s+", body)) if s]
    keep = sents if len(sents) <= 6 else sents[:3] + sents[-3:]
    out = " ".join(keep)
    return (out[:MAX_SUMMARY_CHARS].rstrip() + "…") if len(out) > MAX_SUMMARY_CHARS else out

def iso(s):
    return datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))

def parse_transcript(path):
    recs = []
    for ln in open(path, encoding="utf-8", errors="replace"):
        ln = ln.strip()
        if ln:
            try:
                recs.append(json.loads(ln))
            except Exception:
                pass
    turns, cur = [], None
    for e in recs:
        t = e.get("type")
        if t == "user" and not e.get("isSidechain"):
            p = text_of(e.get("message", {}).get("content"))
            if p is None:
                continue
            if cur:
                turns.append(cur)
            cur = {"dt": iso(e["timestamp"]), "cwd": e.get("cwd") or "", "prompt": p,
                   "texts": [], "tools": {}, "files": {}, "resp_dt": None}
        elif t == "assistant" and cur is not None:
            cur["resp_dt"] = iso(e["timestamp"])
            for b in e.get("message", {}).get("content", []):
                if not isinstance(b, dict):
                    continue
                if b.get("type") == "text":
                    cur["texts"].append(b.get("text", ""))
                elif b.get("type") == "tool_use":
                    n = b.get("name", "?")
                    cur["tools"][n] = cur["tools"].get(n, 0) + 1
                    fp = (b.get("input") or {}).get("file_path") or (b.get("input") or {}).get("path")
                    if fp:
                        cur["files"][fp.rsplit("/", 1)[-1]] = True
    if cur:
        turns.append(cur)
    out = []
    for c in turns:
        meta = []
        if c["files"]:
            meta.append("touched: " + ", ".join(c["files"]))
        if c["tools"]:
            meta.append("tools: " + ", ".join(f"{k}×{v}" for k, v in c["tools"].items()))
        out.append({"dt": c["dt"], "cwd": c["cwd"], "prompt": redact(c["prompt"]),
                    "resp_dt": c["resp_dt"] or c["dt"], "summary": redact(summarize(c["texts"])),
                    "meta": redact("  ·  ".join(meta))})
    return out

# ------------------------------------------------------------ already-live -----
def live_sessions(data):
    live = set()
    for f in glob.glob(os.path.join(data, "projects", "*", "log", "*", "*.md")):
        stem = os.path.basename(f)[:-3]
        sid = stem.split(".", 1)[1] if "." in stem else stem
        try:
            if "BACKFILLED" not in open(f, encoding="utf-8", errors="replace").read(600):
                live.add(sid)
        except Exception:
            pass
    return live

BANNER = "> ⚠️ BACKFILLED from ~/.claude (history.jsonl + transcripts); not captured live.\n"

# ------------------------------------------------------------------ main -------
def main():
    ap = argparse.ArgumentParser(description="Seed devbrain from existing Claude Code caches.")
    ap.add_argument("--apply", action="store_true", help="write into the data repo (default: dry-run)")
    ap.add_argument("--data", default=os.environ.get("DEVBRAIN_DATA", os.path.expanduser("~/devbrain-data")))
    ap.add_argument("--claude", default=os.path.expanduser("~/.claude"))
    ap.add_argument("--exclude", default="", help="comma-separated project keys to skip")
    ap.add_argument("--alias", action="append", default=[], help="OLD=key rename (repeatable)")
    ap.add_argument("--roots", default="~,~/Desktop,~/Downloads,~/Dropbox,~/conductor",
                    help="comma-separated roots to scan for live clones (routing)")
    ap.add_argument("--no-memory", action="store_true", help="skip the memory/ harvest")
    args = ap.parse_args()

    data, claude = args.data, args.claude
    exclude = {x for x in args.exclude.split(",") if x}
    aliases = dict(a.split("=", 1) for a in args.alias if "=" in a)
    remote_index = build_remote_index(args.roots.split(","))
    live = live_sessions(data)
    existing = set(os.listdir(os.path.join(data, "projects"))) if os.path.isdir(os.path.join(data, "projects")) else set()

    # ---- harvest logs (transcripts primary, history.jsonl fallback) ----
    transcripts = {os.path.basename(f)[:-6]: f for f in glob.glob(os.path.join(claude, "projects", "*", "*.jsonl"))}
    transcripts = {s: p for s, p in transcripts.items() if s not in live}
    groups = {}
    n_prompts = collections.defaultdict(int)
    n_resp = collections.defaultdict(int)
    n_mem = collections.defaultdict(int)
    conf_of = collections.defaultdict(lambda: "low")
    ORDER = {"high": 3, "medium": 2, "low": 1}
    done_sessions = set()

    def add_entry(cwd, sid, dt, prompt, resp_dt=None, summary=None, meta=None):
        key, conf = route(cwd, remote_index, aliases)
        wt = sanitize(os.path.basename(cwd.rstrip("/"))) or "unknown"
        gk = (key, wt, sanitize(sid) or "nosession", dt.strftime("%Y-%m-%d"), cwd)
        groups.setdefault(gk, []).append((dt, prompt, resp_dt, summary, meta))
        n_prompts[key] += 1
        if summary:
            n_resp[key] += 1
        if ORDER[conf] > ORDER[conf_of[key]]:
            conf_of[key] = conf

    for sid, path in transcripts.items():
        try:
            turns = parse_transcript(path)
        except Exception:
            continue
        if not turns:
            continue
        done_sessions.add(sid)
        for t in turns:
            add_entry(t["cwd"], sid, t["dt"], t["prompt"], t["resp_dt"], t["summary"], t["meta"])

    hist = os.path.join(claude, "history.jsonl")
    if os.path.exists(hist):
        for l in open(hist, encoding="utf-8", errors="replace"):
            try:
                r = json.loads(l)
            except Exception:
                continue
            p = (r.get("display") or "").strip()
            sid = r.get("sessionId") or "nosession"
            if not p or sid in done_sessions or sid in live or p.lstrip().startswith(SYNTHETIC_PREFIXES):
                continue
            dt = datetime.datetime.fromtimestamp(r["timestamp"] / 1000, datetime.timezone.utc)
            add_entry(r.get("project") or "", sid, dt, redact(p))

    # ---- harvest memory stores ----
    memory = collections.defaultdict(dict)   # key -> {filename: redacted_text}
    if not args.no_memory:
        for md in glob.glob(os.path.join(claude, "projects", "*", "memory")):
            # the project dir's transcript tells us the cwd; fall back to slug guess
            cwd = ""
            for tf in glob.glob(os.path.join(os.path.dirname(md), "*.jsonl")):
                try:
                    for ln in open(tf, encoding="utf-8", errors="replace"):
                        c = json.loads(ln).get("cwd")
                        if c:
                            cwd = c; break
                except Exception:
                    pass
                if cwd:
                    break
            if not cwd:   # no transcript left: reconstruct from the slug (best effort)
                cwd = "/" + os.path.basename(os.path.dirname(md)).lstrip("-").replace("-", "/")
            key, kconf = route(cwd, remote_index, aliases)
            if ORDER[kconf] > ORDER[conf_of[key]]:
                conf_of[key] = kconf
            for f in glob.glob(os.path.join(md, "*.md")):
                memory[key][os.path.basename(f)] = redact(open(f, encoding="utf-8", errors="replace").read())
                n_mem[key] += 1

    # ---- manifest ----
    keys = sorted(set(n_prompts) | set(memory), key=lambda k: -(n_prompts[k] + n_mem[k]))
    print(f"{'PROMPTS':>7} {'RESP':>5} {'MEM':>4}  CONF    KEY")
    print("-" * 64)
    total_files = 0
    for k in keys:
        if k in exclude:
            print(f"{'—':>7} {'—':>5} {'—':>4}  skip    {k}  (excluded)")
            continue
        tag = "" if k in existing else "  (NEW)"
        print(f"{n_prompts[k]:7} {n_resp[k]:5} {n_mem[k]:4}  {conf_of[k]:6}  {k}{tag}")

    # ---- write ----
    if not args.apply:
        print(f"\nDRY-RUN. {len(keys)} projects. Re-run with --apply to write into {data}.")
        print("Opt out of a project:  --exclude <key>[,<key>...]   ·   fix routing:  --alias OLD=key")
        return

    for (key, wt, sid, day, cwd), entries in groups.items():
        if key in exclude:
            continue
        entries.sort(key=lambda x: x[0])
        d = os.path.join(data, "projects", key, "log", day)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, f"{wt}.{sid}.md"), "w") as fh:
            fh.write(f"# {key} — {day} — session {sid}\n\n")
            fh.write("> devbrain Stage A raw prompt log. Append-only, source of truth.\n")
            fh.write(f"> worktree: {wt} · cwd: {cwd} · times in UTC\n>\n{BANNER}\n")
            for dt, prompt, resp_dt, summary, meta in entries:
                fh.write(f"## {dt.strftime('%H:%M:%S')}\n\n{prompt}\n\n")
                if summary:
                    fh.write(f"↳ {resp_dt.strftime('%H:%M:%S')} — {summary}\n")
                    if meta:
                        fh.write(f"   {meta}\n")
                    fh.write("\n")
            total_files += 1
    for key, files in memory.items():
        if key in exclude:
            continue
        d = os.path.join(data, "projects", key, "memory")
        os.makedirs(d, exist_ok=True)
        for name, text in files.items():
            with open(os.path.join(d, name), "w") as fh:
                fh.write(text)
    print(f"\nApplied. Wrote logs for {len([k for k in keys if k not in exclude])} projects + memory stores into {data}.")
    print("Next: run /distill (or /continue) per project to fold this into searchable brain pages.")

if __name__ == "__main__":
    main()
