// Package redact strips high-confidence secret shapes from captured text and
// filters synthetic (harness-injected) prompts. It is the Go port of the
// _REDACT table and SYNTHETIC_PREFIXES in the legacy devbrain_lib.py; the
// contract is pinned byte-for-byte by testdata/golden/redact.golden and
// prompt-filter.jsonl.
package redact

import (
	"regexp"
	"strings"
)

// High-confidence, prefix-anchored secret shapes. Order matters: patterns are
// applied sequentially over the whole text, same as the legacy table.
var rules = []struct {
	re   *regexp.Regexp
	repl string
}{
	{regexp.MustCompile(`sk-[A-Za-z0-9_-]{20,}`), "[REDACTED]"},
	{regexp.MustCompile(`(gh[pousr]_)[A-Za-z0-9]{20,}`), "${1}[REDACTED]"},
	{regexp.MustCompile(`github_pat_[A-Za-z0-9_]{20,}`), "[REDACTED]"},
	{regexp.MustCompile(`(AKIA|ASIA)[0-9A-Z]{16}`), "[REDACTED]"},
	{regexp.MustCompile(`xox[baprs]-[A-Za-z0-9-]{10,}`), "[REDACTED]"},
	{regexp.MustCompile(`(Bearer )[A-Za-z0-9._-]{16,}`), "${1}[REDACTED]"},
}

// Redact replaces secret-shaped substrings with [REDACTED].
func Redact(text string) string {
	if text == "" {
		return text
	}
	for _, r := range rules {
		text = r.re.ReplaceAllString(text, r.repl)
	}
	return text
}

// Injected "prompts" that carry no user authorship at all — pure host-harness
// noise. Kept MINIMAL and biased toward keeping: only markers whose entire
// body is machine-generated with zero user content.
var syntheticPrefixes = []string{
	"<system-reminder>",
	"<command-name>",
	"You are generating a short conversation title",
	"Caveat: The messages below were generated by the user",
	"Base directory for this skill:",
	"<skill>",
}

// IsSynthetic reports whether a prompt is harness-injected noise to skip.
func IsSynthetic(text string) bool {
	if text == "" {
		return false
	}
	s := strings.TrimLeftFunc(text, isSpace)
	for _, p := range syntheticPrefixes {
		if strings.HasPrefix(s, p) {
			return true
		}
	}
	return false
}

// isSpace matches Python str.lstrip()'s default whitespace set closely enough
// for prompt text (ASCII + unicode space classes).
func isSpace(r rune) bool {
	switch r {
	case ' ', '\t', '\n', '\r', '\v', '\f', 0x1c, 0x1d, 0x1e, 0x1f, 0x85:
		return true
	}
	return r == 0xa0 || (r >= 0x2000 && r <= 0x200a) || r == 0x2028 || r == 0x2029 || r == 0x202f || r == 0x205f || r == 0x3000 || r == 0x1680
}

// PromptFilter returns the redacted prompt, or "" when the prompt is
// synthetic (the caller skips capture). Mirrors the legacy prompt-filter CLI.
func PromptFilter(text string) string {
	if IsSynthetic(text) {
		return ""
	}
	return Redact(text)
}
