// Package redact strips secret shapes from captured text and filters synthetic
// (harness-injected) prompts. The prefix-anchored shapes and SYNTHETIC_PREFIXES
// originate in the legacy devbrain_lib.py; the generic env-assignment rule and
// bare-vendor prefixes are Go-only additions. The contract is pinned by
// testdata/golden/redact.golden and prompt-filter.jsonl.
package redact

import (
	"regexp"
	"strings"
)

// High-confidence, prefix-anchored secret shapes. Order matters: patterns are
// applied sequentially over the whole text, same as the legacy table.
var rules = []struct {
	re   *regexp.Regexp
	repl string
}{
	{regexp.MustCompile(`sk-[A-Za-z0-9_-]{20,}`), "[REDACTED]"},
	{regexp.MustCompile(`(gh[pousr]_)[A-Za-z0-9]{20,}`), "${1}[REDACTED]"},
	{regexp.MustCompile(`github_pat_[A-Za-z0-9_]{20,}`), "[REDACTED]"},
	{regexp.MustCompile(`(AKIA|ASIA)[0-9A-Z]{16}`), "[REDACTED]"},
	{regexp.MustCompile(`xox[baprs]-[A-Za-z0-9-]{10,}`), "[REDACTED]"},
	{regexp.MustCompile(`(Bearer )[A-Za-z0-9._-]{16,}`), "${1}[REDACTED]"},
	// Vendor prefixes seen leaking as bare tokens (no `sk-`-style hyphen).
	{regexp.MustCompile(`\bsk[A-Za-z0-9]{32,}`), "[REDACTED]"},                                            // Sanity, and other sk<alnum> tokens
	{regexp.MustCompile(`\bvcp_[A-Za-z0-9]{16,}`), "[REDACTED]"},                                          // Vercel
	{regexp.MustCompile(`\bfc-[A-Za-z0-9]{20,}`), "[REDACTED]"},                                           // Firecrawl
	{regexp.MustCompile(`\bpplx-[A-Za-z0-9]{20,}`), "[REDACTED]"},                                         // Perplexity
	{regexp.MustCompile(`\b(?:pk|sk)1_[A-Za-z0-9]{20,}`), "[REDACTED]"},                                   // Porkbun API / secret key
	{regexp.MustCompile(`\bapify_api_[A-Za-z0-9]{20,}`), "[REDACTED]"},                                    // Apify
	{regexp.MustCompile(`\bsb_(?:secret|publishable)_[A-Za-z0-9_-]{16,}`), "[REDACTED]"},                  // Supabase
	{regexp.MustCompile(`\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}`), "[REDACTED]"}, // JWT
	// PEM private-key blocks (multi-line blobs).
	{regexp.MustCompile(`(?s)-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----.*?-----END [A-Z0-9 ]*PRIVATE KEY-----`), "[REDACTED]"},
	// Generic env-file assignment: redact the value of any NAME=... line whose
	// name has a secret-shaped underscore-delimited segment (KEY, TOKEN, …).
	// Line-anchored + uppercase segments so it only fires on pasted .env / export
	// lines, not inline `key=` in URLs or prose. Catches unknown vendors by name.
	// `\S.{5,}` (≥6 chars, to end of line) so quoted values with spaces redact whole.
	{regexp.MustCompile(`(?m)^([ \t]*(?:export[ \t]+)?(?:[A-Z0-9]+_)*(?:API_?KEY|KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIALS?|AUTH)(?:_[A-Z0-9]+)*[ \t]*=[ \t]*)\S.{5,}`), "${1}[REDACTED]"},
}

// Chat / prose handoffs: "Semrush api key: <value>", "Secret Key:<tab><value>",
// "password: <value>". Case-insensitive label, a ':' separator (inline `key=value`
// is deliberately left to the line-anchored env rule above — the golden corpus
// pins that in-prose `api_key=…` stays), then ONE token of at least 8 non-space
// characters. Values opening with <, [, $ or { are placeholders ("<your-key>",
// "[REDACTED]", "${VAR}") and stay untouched.
var labelRe = regexp.MustCompile(`(?i)\b((?:api[ _-]?key|secret[ _-]?key|access[ _-]?key|private[ _-]?key|client[ _-]?secret|secret|token|password|passwd|passcode)[ \t]*:[ \t]*)([^\s<\[$\{][^\s]{7,})`)

// A real credential almost always carries a digit or a symbol; a plain word after
// "token:" or "password:" in prose ("the token: authentication") is left alone.
var secretish = regexp.MustCompile(`[0-9_\-/+=#!@$%^&*.]`)

func redactLabels(text string) string {
	return labelRe.ReplaceAllStringFunc(text, func(m string) string {
		sub := labelRe.FindStringSubmatch(m)
		if len(sub) < 3 || !secretish.MatchString(sub[2]) {
			return m
		}
		return sub[1] + "[REDACTED]"
	})
}

// Redact replaces secret-shaped substrings with [REDACTED].
func Redact(text string) string {
	if text == "" {
		return text
	}
	for _, r := range rules {
		text = r.re.ReplaceAllString(text, r.repl)
	}
	return redactLabels(text)
}

// Injected "prompts" that carry no user authorship at all — pure host-harness
// noise. Kept MINIMAL and biased toward keeping: only markers whose entire
// body is machine-generated with zero user content.
var syntheticPrefixes = []string{
	"<system-reminder>",
	"<command-name>",
	"You are generating a short conversation title",
	"Caveat: The messages below were generated by the user",
	"Base directory for this skill:",
	"<skill>",
}

// IsSynthetic reports whether a prompt is harness-injected noise to skip.
func IsSynthetic(text string) bool {
	if text == "" {
		return false
	}
	s := strings.TrimLeftFunc(text, isSpace)
	for _, p := range syntheticPrefixes {
		if strings.HasPrefix(s, p) {
			return true
		}
	}
	return false
}

// isSpace matches Python str.lstrip()'s default whitespace set closely enough
// for prompt text (ASCII + unicode space classes).
func isSpace(r rune) bool {
	switch r {
	case ' ', '\t', '\n', '\r', '\v', '\f', 0x1c, 0x1d, 0x1e, 0x1f, 0x85:
		return true
	}
	return r == 0xa0 || (r >= 0x2000 && r <= 0x200a) || r == 0x2028 || r == 0x2029 || r == 0x202f || r == 0x205f || r == 0x3000 || r == 0x1680
}

// PromptFilter returns the redacted prompt, or "" when the prompt is
// synthetic (the caller skips capture). Mirrors the legacy prompt-filter CLI.
func PromptFilter(text string) string {
	if IsSynthetic(text) {
		return ""
	}
	return Redact(text)
}
